In [2]:
import sys
sys.path.append('../')
import torch
from transformer.mask import create_encoder_mask
# Initiate encoder_input_ids and pad_token_id
encoder_input_ids = torch.tensor([ 2, 68, 72, 3, 1, 1])
pad_token_id = torch.tensor([1])

# Create encoder mask
encoder_mask = create_encoder_mask(encoder_input_ids, pad_token_id)

print("encoder_input_ids: \n", encoder_input_ids)
print("encoder_input_ids shape: \n", encoder_input_ids.shape)
print("\n")
print("encoder_mask: \n", encoder_mask)
print("encoder_mask shape: \n", encoder_mask.shape)

encoder_input_ids: 
 tensor([ 2, 68, 72,  3,  1,  1])
encoder_input_ids shape: 
 torch.Size([6])


encoder_mask: 
 tensor([[[1, 1, 1, 1, 0, 0]]], dtype=torch.int32)
encoder_mask shape: 
 torch.Size([1, 1, 6])


In [3]:
import sys
sys.path.append('../')
import torch
from transformer.mask import create_padding_mask, create_causal_mask, create_decoder_mask

# Create the inputs 
decoder_input_ids = torch.tensor([ 2, 68, 72, 96, 1])
pad_token_id = torch.tensor([1]) # padding token ID
seq_len = 5 # sequence length


print("decoder_input_ids:", decoder_input_ids)
print("decoder_input_ids shape:", decoder_input_ids.shape)
print("\n")

# Create padding mask
padding_mask = create_padding_mask(decoder_input_ids, pad_token_id) # (1, seq_len)
print("padding_mask: \n", padding_mask)
print("padding_mask shape:", padding_mask.shape)
print("\n")

decoder_input_ids: tensor([ 2, 68, 72, 96,  1])
decoder_input_ids shape: torch.Size([5])


padding_mask: 
 tensor([[1, 1, 1, 1, 0]], dtype=torch.int32)
padding_mask shape: torch.Size([1, 5])




In [4]:
# Create a causal mask 
causal_mask = create_causal_mask(seq_len)
print('causal_mask: \n', causal_mask)
print('causal_mask shape:', causal_mask.shape)
print("\n")

# Create decoder mask
decoder_mask = create_decoder_mask(decoder_input_ids, pad_token_id, seq_len)
print('decoder_mask: \n', decoder_mask)
print('decoder_mask shape:', decoder_mask.shape)

causal_mask: 
 tensor([[[ True, False, False, False, False],
         [ True,  True, False, False, False],
         [ True,  True,  True, False, False],
         [ True,  True,  True,  True, False],
         [ True,  True,  True,  True,  True]]])
causal_mask shape: torch.Size([1, 5, 5])


decoder_mask: 
 tensor([[[1, 0, 0, 0, 0],
         [1, 1, 0, 0, 0],
         [1, 1, 1, 0, 0],
         [1, 1, 1, 1, 0],
         [1, 1, 1, 1, 0]]], dtype=torch.int32)
decoder_mask shape: torch.Size([1, 5, 5])


In [5]:
import sys
sys.path.append('../')
import torch
from transformer.mask import *

# Create the inputs 
en_input_ids = torch.tensor([ 2, 68, 72, 3, 1])
de_input_ids = torch.tensor([ 2, 68, 72, 96, 1])
pad_id = torch.tensor([1]) # pad token id
seq_len = 5 # sequence length

# Create encoder mask
encoder_mask = create_encoder_mask(en_input_ids, pad_id) 
# (1, 1, seq_len)

# Create padding mask
padding_mask = create_padding_mask(de_input_ids, pad_id) 
# (1, seq_len)

# Create a causal mask 
causal_mask = create_causal_mask(seq_len)
# (1, seq_len, seq_len)

# Create decoder mask
decoder_mask = create_decoder_mask(de_input_ids, pad_id, seq_len)
# (1, seq_len, seq_len)