In [1]:
import torch
import numpy as np

# create an input tensor
input_tensor = torch.tensor([0.123, 0.264, -np.inf])

# apply softmax to the input tensor to obtain the output tensor
output_tensor = torch.softmax(input_tensor, dim=0)

print("input_tensor: \n", input_tensor)
print("output_tensor: \n", output_tensor)

input_tensor: 
 tensor([0.1230, 0.2640,   -inf])
output_tensor: 
 tensor([0.4648, 0.5352, 0.0000])


In [2]:
import torch
import numpy as np

# create an input tensor
input_tensor = torch.tensor([1.0, 2.0, 4.0])

# apply softmax to the input tensor to obtain the output tensor
output_tensor = torch.softmax(input_tensor, dim=0)

print("input_tensor: \n", input_tensor)
print("output_tensor: \n", output_tensor)

input_tensor: 
 tensor([1., 2., 4.])
output_tensor: 
 tensor([0.0420, 0.1142, 0.8438])


In [3]:
denominator = np.exp(1.0) + np.exp(2.0) + np.exp(4.0)

In [4]:
y0 = np.exp(1.0)/denominator
y0 

0.04201006613406605

In [5]:
y1 = np.exp(2.0)/denominator
y1 

0.11419519938459449

In [6]:
y2= np.exp(4.0)/denominator
y2 

0.8437947344813395